# Generated by Django 2.0.2 on 2018-02-15 10:38

from django.contrib.auth.models import Group
from django.db import migrations

groups = ['student', 'technical_lead', 'staff']


def create_groups(apps, schema_editor):
    for group in groups:
        Group.objects.create(name=group)


def remove_groups(apps, schema_editor):
    Group.objects.filter(name__in=groups).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [migrations.RunPython(create_groups, remove_groups)]
