# Generated by Django 2.0.2 on 2018-02-15 10:38

from django.apps import apps
from django.contrib.auth.management import create_permissions
from django.contrib.auth.models import Group
from django.contrib.auth.models import Permission
from django.db import migrations

groups = {
    'project_owner': [
        'add_project',
        'change_project',
        'add_projectusermembership',
        'change_projectusermembership',
    ]
}


def create_groups(apps, schema_editor):

    # Ensure all permissions for all apps have been created
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None

    for group, permissions in groups.items():
        g = Group.objects.create(name=group)
        for permission in Permission.objects.filter(codename__in=permissions):
            g.permissions.add(permission)


def remove_groups(apps, schema_editor):
    Group.objects.filter(name__in=list(groups.keys())).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [migrations.RunPython(create_groups, remove_groups)]
