# Generated by Django 2.0.2 on 2018-06-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_project_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='profile',
            name='uid_number',
            field=models.PositiveIntegerField(null=True, verbose_name='UID Number'),
        ),
    ]
