# Generated by Django 2.0.2 on 2018-03-15 13:44

import django.db.models.deletion

from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_create_permission_groups_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shibboleth_username', models.CharField(blank=True, max_length=50)),
                ('scw_username', models.CharField(blank=True, max_length=50, verbose_name='SCW username')),
                ('account_status',
                 models.PositiveSmallIntegerField(
                     choices=[
                         (1, 'Awaiting Approval'),
                         (2, 'Approved'),
                         (3, 'Declined'),
                         (4, 'Revoked'),
                         (5, 'Suspended'),
                         (6, 'Closed'),
                     ],
                     default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                              to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
