# Generated by Django 2.0.2 on 2018-03-15 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0001_initial'),
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
        migrations.AddField(
            model_name='profile',
            name='institution',
            field=models.ForeignKey(default=1, help_text='Institution user is based', on_delete=django.db.models.deletion.CASCADE, to='institution.Institution'),
            preserve_default=False,
        ),
    ]
