# Generated by Django 2.0.2 on 2018-06-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180611_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='previous_account_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Awaiting Approval'), (1, 'Approved'), (2, 'Declined'), (3, 'Revoked'), (4, 'Suspended'), (5, 'Closed')], default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Awaiting Approval'), (1, 'Approved'), (2, 'Declined'), (3, 'Revoked'), (4, 'Suspended'), (5, 'Closed')], default=0),
        ),
    ]
