# Generated by Django 2.0.2 on 2018-04-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180315_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='hpcw_email',
            field=models.EmailField(blank=True, help_text='HPCW email address', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='hpcw_username',
            field=models.CharField(blank=True, help_text='HPCW username', max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='profile',
            name='raven_email',
            field=models.EmailField(blank=True, help_text='Raven email address', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='raven_username',
            field=models.CharField(blank=True, help_text='Raven username', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='shibboleth_username',
            field=models.CharField(blank=True, help_text='Institutional address', max_length=50),
        ),
    ]
