# Generated by Django 2.0.2 on 2018-04-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180411_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hpcw_email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='HPCW email address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hpcw_username',
            field=models.CharField(blank=True, max_length=50, verbose_name='HPCW username'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='raven_email',
            field=models.EmailField(blank=True, max_length=100, verbose_name='Raven email address'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='raven_username',
            field=models.CharField(blank=True, max_length=50, verbose_name='Raven username'),
        ),
    ]
