# Generated by Django 2.0.2 on 2018-04-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_enable_students_to_create_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
