# Generated by Django 2.0.2 on 2018-07-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_reason_for_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='accepted_terms_and_conditions',
            field=models.BooleanField(default=False, help_text='Designates whether this user has accepted the terms and conditions.', verbose_name='Accepted terms and conditions'),
        ),
    ]
