# Generated by Django 2.0.2 on 2018-07-03 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_accepted_terms_and_conditions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='accepted_terms_and_conditions',
            field=models.BooleanField(default=False, verbose_name='Terms and Conditions'),
        ),
    ]
