# Generated by Django 2.0.2 on 2018-08-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180808_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_shibboleth_login_required',
            field=models.BooleanField(
                default=True,
                help_text=
                'Designates whether this user is required to log in via a shibboleth identity provider.',
                verbose_name='shibboleth login required status'),
        ),
    ]
