# Generated by Django 2.0.2 on 2018-08-29 16:01

from django.contrib.auth.management import create_permissions
from django.contrib.auth.models import Group
from django.contrib.auth.models import Permission
from django.db import migrations

groups = {
    'funding_source_pi': [
        'change_funding_source_membership',
    ],
}


def create_groups(apps, schema_editor):

    # Ensure all permissions for all apps have been created
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None

    for group, permissions in groups.items():
        g = Group.objects.create(name=group)
        for permission in Permission.objects.filter(codename__in=permissions):
            g.permissions.add(permission)


def remove_groups(apps, schema_editor):
    Group.objects.filter(name__in=list(groups.keys())).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180820_1551'),
        ('funding', '0008_auto_20180829_1156'),
    ]

    operations = [migrations.RunPython(create_groups, remove_groups)]
