# Generated by Django 2.0.2 on 2018-08-29 16:01

from django.contrib.auth.models import Permission
from django.contrib.contenttypes.models import ContentType
from django.db import migrations


def create_permission(apps, schema_editor):
    FundingSource = apps.get_model('funding', 'FundingSource')

    content_type = ContentType.objects.get_for_model(FundingSource)
    Permission.objects.create(
        codename='approve_funding_sources',
        name='Can Approve Funding Sources',
        content_type=content_type
    )


def remove_permission(apps, schema_editor):
    Permission.objects.filter(codename='approve_funding_sources').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_funding_source_pi_20180829_1601'),
    ]

    operations = [migrations.RunPython(create_permission, remove_permission)]
