# Generated by Django 2.2.13 on 2020-11-16 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_userlastlogin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlastlogin',
            options={'verbose_name_plural': 'Users Last Login'},
        ),
    ]
