# Generated by Django 2.0.2 on 2018-09-19 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_attribution_20180829_1602'),
        ('users', '0010_auto_20180808_1339'),
    ]

    operations = [
    ]
