# Generated by Django 2.1.2 on 2019-03-04 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_customuser_join_mailing_list'),
        ('users', '0013_merge_20180919_1517'),
    ]

    operations = [
    ]
