# Generated by Django 2.1.7 on 2019-07-30 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_merge_20190304_1239'),
        ('users', '0003_auto_20180514_1306'),
    ]

    operations = [
    ]
