# Generated by Django 2.1.4 on 2019-08-02 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_merge_20190730_1233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='join_mailing_list',
        ),
    ]
