# Generated by Django 2.1.4 on 2019-08-15 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_customuser_join_mailing_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shibbolethprofile',
            old_name='institution',
            new_name='institution_legacy',
        ),
    ]
