# Generated by Django 2.1.4 on 2019-08-15 09:03

from django.db import migrations

def forwards(apps, schema_editor):
    ShibbolethProfile = apps.get_model('users', 'ShibbolethProfile')

    for shib_profile in ShibbolethProfile.objects.all():
        shib_profile.institution = shib_profile.institution_legacy

def backwards(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_profile_institution'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
