# Generated by Django 2.1.4 on 2019-08-15 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20190815_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shibbolethprofile',
            name='institution_legacy',
        ),
    ]
