# Generated by Django 2.0.2 on 2018-05-15 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0007_auto_20180514_1306'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemToInstitutionMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution.Institution')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.System')),
            ],
            options={
                'verbose_name_plural': 'System to Institution Mappings',
            },
        ),
        migrations.AlterUniqueTogether(
            name='systemtoinstitutionmap',
            unique_together={('system', 'institution')},
        ),
    ]
