# Generated by Django 2.2.13 on 2020-11-16 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20201116_2149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='operatingsystem',
            options={'verbose_name_plural': 'Operating Systems'},
        ),
    ]
