# Generated by Django 2.2.13 on 2020-11-20 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20201120_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partition',
            name='system',
        ),
        migrations.AddField(
            model_name='partition',
            name='hardware_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.HardwareGroup'),
        ),
    ]
