# Generated by Django 2.2.13 on 2020-11-18 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20201116_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.System'),
        ),
        migrations.AlterField(
            model_name='queue',
            name='os',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.OperatingSystem'),
        ),
    ]
