# Generated by Django 2.2.13 on 2020-12-09 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20201120_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='partition',
            name='partition_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Core'), (1, 'Research')], default=0, verbose_name='Partition Type'),
        ),
    ]
