# Generated by Django 2.2.13 on 2020-11-19 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_cluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queue',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Cluster'),
        ),
    ]
