version: '3'
services:
    mysql:
        restart: always
        image: "mariadb:5.5"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: cogs3
        ports:
          - "3306:3306"
        volumes:
          - mysql-data:/var/lib/mysql
    redis:
        restart: always
        image: "redis:3.2.12"
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
    web:
        restart: always
        build: .
        command: python3 manage.py runserver 0.0.0.0:5000
        ports:
            - "5000:5000"
        volumes:
            - .:/app/
        depends_on: 
            - mysql
            - redis
volumes:
    mysql-data:
    redis-data: