# Generated by Django 2.2.2 on 2019-07-16 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0069_auto_20190710_1428'),
    ]

    operations = [
        migrations.CreateModel(
            name='slurm_priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_now_add=True)),
                ('Priority_Level', models.IntegerField(default=0, help_text='Calculated priority level for this project', verbose_name='Priority Level')),
                ('project_code', models.ForeignKey(help_text='Project that the calculated priorities are associated with', on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
    ]
