# Generated by Django 2.2.2 on 2019-07-16 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('priority', '0003_auto_20190716_1445'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slurm_priority',
            options={'managed': False},
        ),
    ]
