# Generated by Django 2.2.2 on 2019-07-16 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('priority', '0004_auto_20190716_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slurm_priority',
            options={},
        ),
    ]
