# Generated by Django 2.2.2 on 2019-07-17 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('priority', '0006_auto_20190716_1450'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slurm_priority',
            old_name='project_code',
            new_name='Account',
        ),
    ]
