# Generated by Django 2.2.2 on 2019-07-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priority', '0008_slurm_priority_cpu_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slurm_priority',
            name='Priority_Level',
        ),
        migrations.AddField(
            model_name='slurm_priority',
            name='Ap',
            field=models.IntegerField(default=50000, help_text='Calculated Attribution points for this project', verbose_name='Attribution points (Ap)'),
        ),
        migrations.AddField(
            model_name='slurm_priority',
            name='Qos',
            field=models.IntegerField(default=0, help_text='Quality of service value for this project, to be input into slurm.', verbose_name='Quality of Service (QOS)'),
        ),
        migrations.AddField(
            model_name='slurm_priority',
            name='prioritized_time',
            field=models.IntegerField(default=0, help_text='Sum of priortized cpu time alocated to this project', verbose_name='Total prioritized time'),
        ),
    ]
