# Generated by Django 2.2.2 on 2019-07-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priority', '0009_auto_20190717_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='slurm_priority',
            name='GPU_hours',
            field=models.IntegerField(default=0, help_text='GPU compute hours used since this project began', verbose_name='Total Gpu hours'),
        ),
        migrations.AddField(
            model_name='slurm_priority',
            name='P_CPU',
            field=models.IntegerField(default=0, help_text='Total CPU compute hours in a priortized state since this project began', verbose_name='prioritized Cpu hours'),
        ),
        migrations.AddField(
            model_name='slurm_priority',
            name='P_GPU',
            field=models.IntegerField(default=0, help_text='Total GPU compute hours in a priortized state since this project began', verbose_name='prioritized Gpu hours'),
        ),
        migrations.AlterField(
            model_name='slurm_priority',
            name='CPU_hours',
            field=models.IntegerField(default=0, help_text='cpu comute hours used since this project began', verbose_name='Total Cpu hours'),
        ),
        migrations.AlterField(
            model_name='slurm_priority',
            name='Date',
            field=models.DateField(),
        ),
    ]
