# Generated by Django 2.2.2 on 2019-07-19 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('priority', '0010_auto_20190719_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slurm_priority',
            name='prioritized_time',
        ),
    ]
