# Generated by Django 2.2.4 on 2019-08-13 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('priority', '0012_auto_20190813_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slurmpriority',
            old_name='account',
            new_name='project_code',
        ),
    ]
