# Generated by Django 2.2.4 on 2019-08-13 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('priority', '0013_auto_20190813_2227'),
    ]

    operations = [
       migrations.RenameField('SlurmPriority', 'project_code', 'account')
    ]
