# Generated by Django 2.2.4 on 2019-08-14 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('priority', '0014_auto_20190813_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slurmpriority',
            old_name='AP',
            new_name='attribution_points',
        ),
        migrations.RenameField(
            model_name='slurmpriority',
            old_name='QOS',
            new_name='quality_of_service',
        ),
        migrations.AlterField(
            model_name='slurmpriority',
            name='account',
            field=models.CharField(max_length=20, verbose_name='Slurm account name'),
        ),
    ]
