# Generated by Django 2.2.13 on 2020-12-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computedaily',
            name='number_processors',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
