# Generated by Django 2.2.13 on 2020-11-16 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accessmethod',
            options={'verbose_name_plural': 'Access Methods'},
        ),
        migrations.AlterModelOptions(
            name='dailystat',
            options={'verbose_name_plural': 'Daily Stats'},
        ),
        migrations.AlterModelOptions(
            name='numberofprocessors',
            options={'verbose_name_plural': 'Number Of Processors'},
        ),
        migrations.AlterModelOptions(
            name='weeklystatstorageprojectscf',
            options={'verbose_name_plural': 'Weekly Stats Storage Projects CF'},
        ),
    ]
