# Generated by Django 2.2.13 on 2021-05-10 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_computedaily_number_processors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='computedaily',
            options={'get_latest_by': 'date', 'verbose_name_plural': 'Compute Daily'},
        ),
        migrations.AlterModelOptions(
            name='storageweekly',
            options={'get_latest_by': 'date', 'verbose_name_plural': 'Storage Weekly'},
        ),
    ]
