# Generated by Django 2.2.13 on 2020-11-18 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0002_auto_20201116_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystat',
            name='access_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.AccessMethod'),
        ),
        migrations.AlterField(
            model_name='dailystat',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.Application'),
        ),
        migrations.AlterField(
            model_name='dailystat',
            name='number_of_processors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stats.NumberOfProcessors'),
        ),
        migrations.AlterField(
            model_name='dailystat',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Project'),
        ),
        migrations.AlterField(
            model_name='dailystat',
            name='queue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Queue'),
        ),
        migrations.AlterField(
            model_name='dailystat',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weeklystatstorageprojectscf',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.Phase'),
        ),
        migrations.AlterField(
            model_name='weeklystatstorageprojectscf',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.Project'),
        ),
    ]
