# Generated by Django 2.0.2 on 2018-06-20 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('project', '0027_rename_funding_source')
    ]

    state_operations = [
        migrations.CreateModel(
            name='FundingBody',
            fields=[
                (
                    'id',
                    models.AutoField(
                        verbose_name='ID',
                        serialize=False,
                        auto_created=True,
                        primary_key=True,
                    )
                ),
            ],
            options={
                'db_table': 'funding.FundingBody',
            },
            bases=(models.Model,),
        )
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=state_operations,
        ),
        migrations.CreateModel(
            name='FundingSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('identifier', models.CharField(max_length=512)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('funding_body', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='funding.FundingBody', verbose_name='Funding Body')),
            ],
            options={
                'verbose_name_plural': 'Project Funding Sources',
                'ordering': ('created_time',),
            },
        ),
    ]
