# Generated by Django 2.0.2 on 2018-06-20 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0002_auto_20180620_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundingbody',
            options={'ordering': ('name',), 'verbose_name_plural': 'Funding Bodies'},
        ),
        migrations.AlterModelOptions(
            name='fundingsource',
            options={'ordering': ('created_time',), 'verbose_name_plural': 'Funding Sources'},
        ),
    ]
