# Generated by Django 2.0.2 on 2018-06-20 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funding', '0003_auto_20180620_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingsource',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='fundingsource',
            name='pi_email',
            field=models.CharField(default='j.m.o.rantaharju@swansea.ac.uk', max_length=128),
            preserve_default=False,
        ),
    ]
