# Generated by Django 2.0.2 on 2018-06-20 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0004_auto_20180620_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingsource',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
    ]
