# Generated by Django 2.0.2 on 2018-06-22 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funding', '0005_auto_20180620_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingsource',
            name='pi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pi', to=settings.AUTH_USER_MODEL, verbose_name='PI'),
        ),
        migrations.AlterField(
            model_name='fundingsource',
            name='pi_email',
            field=models.CharField(max_length=128, verbose_name='PI Email'),
        ),
    ]
