# Generated by Django 2.0.2 on 2018-08-29 09:55

from django.db import migrations


def forwards(apps, schema_editor):
    # Add the creator to the list of users
    FundingSource = apps.get_model('funding', 'FundingSource')
    FundingSourceMembership = apps.get_model('funding', 'FundingSourceMembership')

    for fs in FundingSource.objects.all():
        FundingSourceMembership.objects.create(
            user=fs.created_by,
            fundingsource=fs,
            approved=False,
        )


def backwards(apps, schema_editor):
    # Remove the creator from the list
    FundingSource = apps.get_model('funding', 'FundingSource')
    FundingSourceMembership = apps.get_model('funding', 'FundingSourceMembership')

    for fs in FundingSource.objects.all():
        FundingSourceMembership.objects.filter(
            user=fs.created_by,
            fundingsource=fs,
        ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0006_auto_20180829_0942'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
