# Generated by Django 2.0.2 on 2018-06-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0006_auto_20180622_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingsource',
            name='pi_email',
            field=models.CharField(max_length=128, null=True, verbose_name='PI Email'),
        ),
    ]
