# Generated by Django 2.0.2 on 2018-08-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        ('funding', '0007_fundingsource_users_20180829_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingsource',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Atributed to HPCW by the PI'),
        ),
        migrations.AddField(
            model_name='historicalfundingsource',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Atributed to HPCW by the PI'),
        ),
    ]
