# Generated by Django 2.0.2 on 2018-08-29 15:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0008_auto_20180829_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingsourcemembership',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fundingsourcemembership',
            name='modified_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
