# Generated by Django 2.0.2 on 2018-08-31 15:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('funding', '0010_auto_20180831_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribution',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='fundingsource',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Atributed to SCW by the PI'),
        ),
        migrations.AlterField(
            model_name='historicalfundingsource',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Atributed to SCW by the PI'),
        ),
        migrations.AlterUniqueTogether(
            name='fundingsourcemembership',
            unique_together={('user', 'fundingsource')},
        ),
    ]
