# Generated by Django 2.1.7 on 2019-07-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0011_auto_20180831_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingsource',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Attributed to SCW by the PI'),
        ),
        migrations.AlterField(
            model_name='fundingsource',
            name='pi_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='PI Email'),
        ),
        migrations.AlterField(
            model_name='historicalfundingsource',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='Attributed to SCW by the PI'),
        ),
        migrations.AlterField(
            model_name='historicalfundingsource',
            name='pi_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='PI Email'),
        ),
    ]
