# Generated by Django 2.1.7 on 2019-07-30 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0013_auto_20190704_1123'),
        ('funding', '0012_auto_20190729_0850'),
    ]

    operations = [
    ]
