#!/bin/bash
HERE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd $HERE
cd ..

rm db.sqlite3
python manage.py migrate
python manage.py loaddata institutions.json $HERE/one-user-per-institution.json systems.json ./funding/fixtures/tests/funding_bodies.json
