# Generated by Django 2.0.2 on 2018-02-13 22:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('institution', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectusermembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectsystemallocation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
        ),
        migrations.AddField(
            model_name='projectsystemallocation',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.System'),
        ),
        migrations.AddField(
            model_name='project',
            name='allocation_systems',
            field=models.ManyToManyField(through='project.ProjectSystemAllocation', to='system.System'),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectCategory'),
        ),
        migrations.AddField(
            model_name='project',
            name='funding_source',
            field=models.ForeignKey(help_text='Funding code from institution', on_delete=django.db.models.deletion.CASCADE, to='project.ProjectFundingSource'),
        ),
        migrations.AddField(
            model_name='project',
            name='institution',
            field=models.ForeignKey(help_text='Institution project is based', on_delete=django.db.models.deletion.CASCADE, to='institution.Institution'),
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(through='project.ProjectUserMembership', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='pi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_as_pi', to=settings.AUTH_USER_MODEL, verbose_name='Principal Investigator'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.ProjectStatus'),
        ),
        migrations.AddField(
            model_name='project',
            name='tech_lead',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_as_tech_lead', to=settings.AUTH_USER_MODEL, verbose_name='Technical Lead'),
        ),
    ]
