# Generated by Django 2.0.2 on 2018-02-14 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180213_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='allocation_cputime',
            field=models.PositiveIntegerField(verbose_name='CPU time allocation in hours'),
        ),
        migrations.AlterField(
            model_name='project',
            name='allocation_storage',
            field=models.PositiveIntegerField(verbose_name='Project group storage allocation in GB'),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectFundingSource'),
        ),
    ]
