# Generated by Django 2.0.2 on 2018-02-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20180214_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Awaiting Approval'), (2, 'Approved'), (3, 'Declined'), (4, 'Revoked'), (5, 'Suspended'), (6, 'Closed')], default=1, help_text='Authorisation status'),
        ),
        migrations.AlterField(
            model_name='projectusermembership',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Awaiting Authorisation'), (2, 'Authorised'), (3, 'Declined'), (4, 'Revoked'), (5, 'Suspended')], default=1, help_text='Authorisation status'),
        ),
        migrations.DeleteModel(
            name='ProjectStatus',
        ),
    ]
