# Generated by Django 2.0.2 on 2018-02-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20180214_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pi',
            field=models.CharField(max_length=256, verbose_name='Principal Investigator'),
        ),
    ]
