# Generated by Django 2.0.2 on 2018-02-19 15:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0009_project_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectusermembership',
            unique_together={('project', 'user')},
        ),
    ]
