# Generated by Django 2.0.2 on 2018-02-20 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_auto_20180219_1521'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectusermembership',
            unique_together=set(),
        ),
    ]
