# Generated by Django 2.0.2 on 2018-02-20 13:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0011_auto_20180220_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=20, unique=True, verbose_name='Project code assigned by SCW'),
        ),
        migrations.AlterUniqueTogether(
            name='projectusermembership',
            unique_together={('project', 'user')},
        ),
    ]
