# Generated by Django 2.0.2 on 2018-05-14 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_project_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectfundingsource',
            options={'ordering': ('name',), 'verbose_name_plural': 'Project Funding Sources'},
        ),
    ]
