# Generated by Django 2.0.2 on 2018-05-14 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_auto_20180514_1306'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'ordering': ('name',), 'verbose_name_plural': 'Project Categories'},
        ),
    ]
