# Generated by Django 2.0.2 on 2018-05-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_auto_20180514_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='allocation_storage',
        ),
        migrations.AddField(
            model_name='project',
            name='allocation_memory',
            field=models.PositiveIntegerField(default=0, verbose_name='RAM allocation in GB'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='allocation_storage_home',
            field=models.PositiveIntegerField(default=0, verbose_name='Home storage in GB'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='allocation_storage_scartch',
            field=models.PositiveIntegerField(default=0, verbose_name='Scratch storage in GB'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='requirements_gateways',
            field=models.TextField(help_text='Web gateway or portal name and versions', max_length=512),
        ),
    ]
