# Generated by Django 2.0.2 on 2018-05-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_auto_20180514_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reason_decision',
            field=models.TextField(blank=True, help_text='This will be emailed to the technical lead.', max_length=256, verbose_name='Reason for the project status decision.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True, help_text='General project notes', max_length=512),
        ),
    ]
