# Generated by Django 2.0.2 on 2018-05-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_auto_20180515_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Project code assigned by SCW'),
        ),
        migrations.AlterField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal project notes', max_length=512),
        ),
        migrations.AlterField(
            model_name='project',
            name='reason_decision',
            field=models.TextField(blank=True, help_text="The reason will be emailed to the project's technical lead upon project status update.", max_length=256, verbose_name='Reason for the project status decision:'),
        ),
    ]
