# Generated by Django 2.0.2 on 2018-05-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_auto_20180515_1256'),
        ('project', '0018_auto_20180515_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsystemallocation',
            name='openldap_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Create System Resources'), (2, 'Created System Resources'), (3, 'Deactivate System Resources'), (4, 'Deactivated System Resources')], default=1, verbose_name='OpenLDAP status'),
        ),
        migrations.AlterField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal project notes', max_length=512),
        ),
        migrations.AlterField(
            model_name='project',
            name='reason_decision',
            field=models.TextField(blank=True, help_text="The reason will be emailed to the project's technical lead upon project status update.", max_length=256, verbose_name='Reason for the project status decision:'),
        ),
        migrations.AlterUniqueTogether(
            name='projectsystemallocation',
            unique_together={('project', 'system')},
        ),
    ]
