# Generated by Django 2.0.2 on 2018-05-16 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_auto_20180516_1034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='allocation_storage_scartch',
            new_name='allocation_storage_scratch',
        ),
    ]
