# Generated by Django 2.0.2 on 2018-05-16 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_auto_20180516_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='allocation_systems',
            field=models.ManyToManyField(through='project.ProjectSystemAllocation', to='system.System', verbose_name='Allocation systems'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.ProjectCategory', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created time'),
        ),
        migrations.AlterField(
            model_name='project',
            name='department',
            field=models.CharField(blank=True, max_length=128, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='project',
            name='economic_user',
            field=models.BooleanField(default=False, verbose_name='Economic user'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding_source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.ProjectFundingSource', verbose_name='Funding source'),
        ),
        migrations.AlterField(
            model_name='project',
            name='institution',
            field=models.ForeignKey(help_text='Institution project is based', on_delete=django.db.models.deletion.CASCADE, to='institution.Institution', verbose_name='Institution'),
        ),
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(through='project.ProjectUserMembership', to=settings.AUTH_USER_MODEL, verbose_name='Members'),
        ),
        migrations.AlterField(
            model_name='project',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Modified time'),
        ),
        migrations.AlterField(
            model_name='project',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal project notes', max_length=512, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='project',
            name='requirements_gateways',
            field=models.TextField(help_text='Web gateway or portal name and versions', max_length=512, verbose_name='Requirements gateways'),
        ),
        migrations.AlterField(
            model_name='project',
            name='requirements_onboarding',
            field=models.TextField(max_length=512, verbose_name='Requirements onboarding'),
        ),
        migrations.AlterField(
            model_name='project',
            name='requirements_software',
            field=models.TextField(help_text='Software name and versions', max_length=512, verbose_name='Requirements software'),
        ),
        migrations.AlterField(
            model_name='project',
            name='requirements_training',
            field=models.TextField(max_length=512, verbose_name='Requirements training'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Awaiting Approval'), (2, 'Approved'), (3, 'Declined'), (4, 'Revoked'), (5, 'Suspended'), (6, 'Closed')], default=1, verbose_name='Status'),
        ),
    ]
