# Generated by Django 2.0.2 on 2018-05-18 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_auto_20180516_1102'),
        ('project', '0020_auto_20180516_1206'),
    ]

    operations = [
    ]
