# Generated by Django 2.0.2 on 2018-05-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_auto_20180515_1314'),
        ('project', '0021_merge_20180518_1307'),
    ]

    operations = [
    ]
