# Generated by Django 2.0.2 on 2018-06-07 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0024_project_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='institution',
        ),
    ]
