# Generated by Django 2.0.2 on 2018-06-25 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_remove_project_institution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='pi',
            new_name='pi_email',
        ),
    ]
