# Generated by Django 2.0.2 on 2018-06-17 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0025_remove_project_institution'),
        ('project', '0025_auto_20180613_1025'),
    ]

    operations = [
    ]
