# Generated by Django 2.0.2 on 2018-06-20 10:59

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('project', '0026_remove_project_funding_source')
    ]

    database_operations = [
        migrations.AlterModelTable('ProjectFundingSource',  'funding.FundingBody'),
    ]

    state_operations = [
        migrations.DeleteModel('ProjectFundingSource')
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations,
        )
    ]
