# Generated by Django 2.0.2 on 2018-06-17 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0026_merge_20180617_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=1024, verbose_name='Project Description'),
        ),
    ]
