# Generated by Django 2.0.2 on 2018-06-25 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0027_auto_20180625_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_as_pi', to=settings.AUTH_USER_MODEL, verbose_name='Principal Investigator'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pi_email',
            field=models.CharField(max_length=128, null=True, verbose_name='Principal Investigator Email'),
        ),
    ]
