# Generated by Django 2.0.2 on 2018-06-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0003_auto_20180620_1251'),
        ('project', '0027_rename_funding_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='funding_sources',
            field=models.ManyToManyField(to='funding.FundingSource'),
        ),
    ]
