# Generated by Django 2.0.2 on 2018-06-26 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0028_auto_20180625_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='pi',
            new_name='project_supervisor',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='pi_email',
            new_name='project_supervisor',
        ),
    ]
