# Generated by Django 2.0.2 on 2018-06-26 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0028_auto_20180625_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='pi',
        ),
        migrations.RemoveField(
            model_name='project',
            name='pi_email',
        ),
        migrations.AddField(
            model_name='project',
            name='project_supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_as_project_supervisor', to=settings.AUTH_USER_MODEL, verbose_name='Project Supervisor'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_supervisor_email',
            field=models.CharField(max_length=128, null=True, verbose_name='Project Supervisor Email'),
        ),
    ]
