# Generated by Django 2.0.2 on 2018-06-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_project_funding_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='funding_sources',
            field=models.ManyToManyField(blank=True, to='funding.FundingSource'),
        ),
    ]
