# Generated by Django 2.0.2 on 2018-06-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0030_auto_20180619_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectusermembership',
            name='previous_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Awaiting Authorisation'), (2, 'Authorised'), (3, 'Declined'), (4, 'Revoked'), (5, 'Suspended')], default=1, verbose_name='Previous Status'),
        ),
        migrations.AlterField(
            model_name='projectusermembership',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Awaiting Authorisation'), (2, 'Authorised'), (3, 'Declined'), (4, 'Revoked'), (5, 'Suspended')], default=1, verbose_name='Current Status'),
        ),
    ]
