# Generated by Django 2.0.2 on 2018-06-20 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0032_auto_20180620_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='allocation_cputime',
            field=models.PositiveIntegerField(blank=True, verbose_name='CPU time allocation in hours'),
        ),
        migrations.AlterField(
            model_name='project',
            name='allocation_memory',
            field=models.PositiveIntegerField(blank=True, verbose_name='RAM allocation in GB'),
        ),
        migrations.AlterField(
            model_name='project',
            name='allocation_storage_home',
            field=models.PositiveIntegerField(blank=True, verbose_name='Home storage in GB'),
        ),
        migrations.AlterField(
            model_name='project',
            name='allocation_storage_scratch',
            field=models.PositiveIntegerField(blank=True, verbose_name='Scratch storage in GB'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pi',
            field=models.CharField(max_length=256, verbose_name="Principal Investigator's name, position and email"),
        ),
    ]
