# Generated by Django 2.0.2 on 2018-06-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_auto_20180620_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='allocation_cputime',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='CPU time allocation in hours'),
        ),
        migrations.AlterField(
            model_name='project',
            name='allocation_memory',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='RAM allocation in GB'),
        ),
        migrations.AlterField(
            model_name='project',
            name='allocation_storage_home',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Home storage in GB'),
        ),
        migrations.AlterField(
            model_name='project',
            name='allocation_storage_scratch',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Scratch storage in GB'),
        ),
    ]
