# Generated by Django 2.0.2 on 2018-06-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_auto_20180623_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='requirements_gateways',
            field=models.TextField(blank=True, help_text='Web gateway or portal name and versions', max_length=512, verbose_name='Gateway Requirements'),
        ),
        migrations.AlterField(
            model_name='project',
            name='requirements_onboarding',
            field=models.TextField(blank=True, max_length=512, verbose_name='Onboarding Requirements'),
        ),
        migrations.AlterField(
            model_name='project',
            name='requirements_software',
            field=models.TextField(blank=True, help_text='Software name and versions', max_length=512, verbose_name='Software Requirements'),
        ),
        migrations.AlterField(
            model_name='project',
            name='requirements_training',
            field=models.TextField(blank=True, max_length=512, verbose_name='Training Requirements'),
        ),
    ]
