# Generated by Django 2.2.13 on 2021-02-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0035_auto_20180626_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'get_latest_by': 'created_time', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AddField(
            model_name='project',
            name='pi_email',
            field=models.EmailField(blank=True, max_length=100, verbose_name="Principal Investigator's email"),
        ),
        migrations.AddField(
            model_name='project',
            name='pi_name',
            field=models.CharField(blank=True, max_length=128, verbose_name="Principal Investigator's name"),
        ),
        migrations.AddField(
            model_name='project',
            name='pi_position',
            field=models.CharField(blank=True, max_length=128, verbose_name="Principal Investigator's position"),
        ),
        migrations.AlterField(
            model_name='project',
            name='pi',
            field=models.CharField(max_length=256, verbose_name="(obsolete) Principal Investigator's name, position and email"),
        ),
    ]
