# Generated by Django 2.0.2 on 2018-07-11 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_auto_20180621_1309'),
        ('project', '0035_auto_20180626_2111'),
    ]

    operations = [
    ]
