# Generated by Django 2.2.13 on 2021-02-01 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0036_auto_20210201_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pi',
            field=models.CharField(blank=True, max_length=256, verbose_name="(obsolete) Principal Investigator's name, position and email"),
        ),
    ]
