# Generated by Django 2.0.2 on 2018-07-12 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0036_merge_20180711_1444'),
        ('project', '0036_auto_20180711_1259'),
    ]

    operations = [
    ]
