# Generated by Django 2.0.2 on 2018-07-17 11:28

from django.db import migrations, models


def forwards(apps, schema_editor):
    Project = apps.get_model('project', 'Project')
    for p in Project.objects.all():
        print('p', p.funding_sources)


def backwards(apps, schema_editor):
    Project = apps.get_model('project', 'Project')
    for p in Project.objects.all():
        print('p', p.funding_sources)


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0001_initial'),
        ('project', '0036_auto_20180711_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='funding_sources',
            field=models.ManyToManyField(blank=True, to='funding.FundingSource'),
        ),
        migrations.RunPython(forwards, backwards),
    ]
