# Generated by Django 2.0.2 on 2018-07-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0001_initial'),
        ('project', '0036_auto_20180711_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='attributions',
            field=models.ManyToManyField(blank=True, to='funding.Attribution'),
        ),
    ]
