# Generated by Django 2.0.2 on 2018-07-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0037_auto_20180717_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='funding_source',
        ),
        migrations.DeleteModel(
            name='ProjectFundingSource',
        ),
    ]
