# Generated by Django 2.2.13 on 2021-05-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0037_auto_20210201_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pi_email',
            field=models.CharField(blank=True, max_length=256, verbose_name="Principal Investigator's email"),
        ),
    ]
