# Generated by Django 2.0.2 on 2018-07-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0039_historicalproject_historicalprojectcategory_historicalprojectsystemallocation_historicalprojectuserm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='pi',
            field=models.CharField(max_length=256, verbose_name="[Deprecated]Principal Investigator's name, position and email"),
        ),
        migrations.AlterField(
            model_name='project',
            name='pi',
            field=models.CharField(max_length=256, verbose_name="[Deprecated]Principal Investigator's name, position and email"),
        ),
        migrations.RenameField(
            model_name='historicalproject',
            old_name='pi',
            new_name='pi_legacy',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='pi',
            new_name='pi_legacy',
        ),
    ]
