# Generated by Django 2.0.2 on 2018-07-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0040_auto_20180731_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='supervisor_email',
            field=models.CharField(blank=True, max_length=256, verbose_name="Project Leader's email"),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=256, verbose_name="Project Leader's name"),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='supervisor_position',
            field=models.CharField(blank=True, max_length=256, verbose_name="Project Leader's position"),
        ),
        migrations.AddField(
            model_name='project',
            name='supervisor_email',
            field=models.CharField(blank=True, max_length=256, verbose_name="Project Leader's email"),
        ),
        migrations.AddField(
            model_name='project',
            name='supervisor_name',
            field=models.CharField(blank=True, max_length=256, verbose_name="Project Leader's name"),
        ),
        migrations.AddField(
            model_name='project',
            name='supervisor_position',
            field=models.CharField(blank=True, max_length=256, verbose_name="Project Leader's position"),
        ),
    ]
