# Generated by Django 2.0.2 on 2018-08-02 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def forwards(apps, schema_editor):
    # Copy relevant information from the project to the allocationrequest
    Project = apps.get_model('project', 'Project')
    SystemAllocationRequest = apps.get_model('project', 'SystemAllocationRequest')

    for project in Project.objects.all():
        allocation = SystemAllocationRequest(
            start_date=project.start_date,
            end_date=project.end_date,
            allocation_rse=project.allocation_rse,
            allocation_cputime=project.allocation_cputime,
            allocation_memory=project.allocation_memory,
            allocation_storage_home=project.allocation_storage_home,
            allocation_storage_scratch=project.allocation_storage_scratch,
            status=project.status,
            previous_status=project.previous_status,
            created_time=project.created_time,
            project=project,
            requirements_software=project.requirements_software,
            requirements_training=project.requirements_training,
            requirements_onboarding=project.requirements_onboarding,
            document=project.document,
            notes=project.notes
        )
        allocation.save()


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0001_initial'),
        ('project', '0037_auto_20180717_1128'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0041_auto_20180731_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAllocationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField(max_length=1024, verbose_name='Additional details of the allocation request not present in the project description')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('allocation_rse', models.BooleanField(default=False, verbose_name='RSE available to?')),
                ('allocation_cputime', models.PositiveIntegerField(blank=True, null=True, verbose_name='CPU time allocation in hours')),
                ('allocation_memory', models.PositiveIntegerField(blank=True, null=True, verbose_name='RAM allocation in GB')),
                ('allocation_storage_home', models.PositiveIntegerField(blank=True, null=True, verbose_name='Home storage in GB')),
                ('allocation_storage_scratch', models.PositiveIntegerField(blank=True, null=True, verbose_name='Scratch storage in GB')),
                ('requirements_software', models.TextField(blank=True, help_text='Software name and versions', max_length=512, verbose_name='Software Requirements')),
                ('requirements_training', models.TextField(blank=True, max_length=512, verbose_name='Training Requirements')),
                ('requirements_onboarding', models.TextField(blank=True, max_length=512, verbose_name='Onboarding Requirements')),
                ('document', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d/%M/', verbose_name='Upload Supporting Documents')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Awaiting Approval'), (1, 'Approved'), (2, 'Declined'), (3, 'Revoked'), (4, 'Suspended'), (5, 'Closed')], default=0, verbose_name='Current Status')),
                ('previous_status', models.PositiveSmallIntegerField(choices=[(0, 'Awaiting Approval'), (1, 'Approved'), (2, 'Declined'), (3, 'Revoked'), (4, 'Suspended'), (5, 'Closed')], default=0, verbose_name='Previous Status')),
                ('reason_decision', models.TextField(blank=True, help_text="The reason will be emailed to the project's technical lead upon project status update.", max_length=256, verbose_name='Reason for the system allocation status decision:')),
                ('notes', models.TextField(blank=True, help_text='Internal notes', max_length=512, verbose_name='Notes')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='Modified time')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_allocation_as_project', to='project.Project', verbose_name='Project')),
            ],
            options={
                'verbose_name_plural': 'System Allocation Requests',
            },
        ),
        migrations.RunPython(forwards, backwards),
    ]
