# Generated by Django 2.0.2 on 2018-08-02 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0042_create_allocation_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalSystemAllocationRequest',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('information', models.TextField(max_length=1024, verbose_name='Additional details of the allocation request not present in the project description')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('allocation_rse', models.BooleanField(default=False, verbose_name='RSE available to?')),
                ('allocation_cputime', models.PositiveIntegerField(blank=True, null=True, verbose_name='CPU time allocation in hours')),
                ('allocation_memory', models.PositiveIntegerField(blank=True, null=True, verbose_name='RAM allocation in GB')),
                ('allocation_storage_home', models.PositiveIntegerField(blank=True, null=True, verbose_name='Home storage in GB')),
                ('allocation_storage_scratch', models.PositiveIntegerField(blank=True, null=True, verbose_name='Scratch storage in GB')),
                ('requirements_software', models.TextField(blank=True, help_text='Software name and versions', max_length=512, verbose_name='Software Requirements')),
                ('requirements_training', models.TextField(blank=True, max_length=512, verbose_name='Training Requirements')),
                ('requirements_onboarding', models.TextField(blank=True, max_length=512, verbose_name='Onboarding Requirements')),
                ('document', models.TextField(blank=True, max_length=100, null=True, verbose_name='Upload Supporting Documents')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Awaiting Approval'), (1, 'Approved'), (2, 'Declined'), (3, 'Revoked'), (4, 'Suspended'), (5, 'Closed')], default=0, verbose_name='Current Status')),
                ('previous_status', models.PositiveSmallIntegerField(choices=[(0, 'Awaiting Approval'), (1, 'Approved'), (2, 'Declined'), (3, 'Revoked'), (4, 'Suspended'), (5, 'Closed')], default=0, verbose_name='Previous Status')),
                ('reason_decision', models.TextField(blank=True, help_text="The reason will be emailed to the project's technical lead upon project status update.", max_length=256, verbose_name='Reason for the system allocation status decision:')),
                ('notes', models.TextField(blank=True, help_text='Internal notes', max_length=512, verbose_name='Notes')),
                ('created_time', models.DateTimeField(blank=True, editable=False, verbose_name='Created time')),
                ('modified_time', models.DateTimeField(blank=True, editable=False, verbose_name='Modified time')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.Project')),
            ],
            options={
                'verbose_name': 'historical system allocation request',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
    ]
