# Generated by Django 2.0.2 on 2018-08-07 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0044_remove_project_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsystemallocationrequest',
            name='information',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Additional details of the allocation request not present in the project description'),
        ),
        migrations.AlterField(
            model_name='systemallocationrequest',
            name='information',
            field=models.TextField(blank=True, max_length=1024, verbose_name='Additional details of the allocation request not present in the project description'),
        ),
    ]
