# Generated by Django 2.0.2 on 2018-08-07 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0045_auto_20180807_1114'),
        ('project', '0045_auto_20180807_1327'),
    ]

    operations = [
    ]
