# Generated by Django 2.0.2 on 2018-08-15 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0046_merge_20180807_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRSEAllocation',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(help_text='A one-sentence summary of the work to be done by the RSE team.', max_length=256, verbose_name='Subproject title')),
                ('software', models.TextField(help_text='The software currently in use to deliver the research outcomes. Questions to consider: Is it commercial, open-source, or in-house code? What language is it written in? What libraries does it depend on? Is it parallelised?', max_length=2000, verbose_name='Software description')),
                ('duration', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Estimated duration (in weeks)')),
                ('goals', models.TextField(help_text='Describe in as much detail as possible what you would like the RSE team to achieve. What steps are necessary to achieve this?', max_length=5000, verbose_name='Project goals')),
                ('outcomes', models.TextField(help_text='What effect will the completion of this work have on your research, e.g. in terms of publications or grants enabled? ', max_length=2000, verbose_name='Project outcomes')),
                ('confidentiality', models.TextField(blank=True, help_text='Is the research or code restricted from being published openly and presented at conferences and other events related to research software? If so, please describe the restrictions.', max_length=1000, verbose_name='Confidentiality constraints')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Awaiting Approval'), (1, 'Approved; awaiting RSE time'), (2, 'Declined'), (3, 'In progress'), (4, 'Completed'), (5, 'Closed')], default=0, verbose_name='Current Status')),
                ('previous_status', models.PositiveSmallIntegerField(choices=[(0, 'Awaiting Approval'), (1, 'Approved; awaiting RSE time'), (2, 'Declined'), (3, 'In progress'), (4, 'Completed'), (5, 'Closed')], default=0, verbose_name='Previous Status')),
                ('reason_decision', models.TextField(blank=True, max_length=256, verbose_name='Reason for the RSE allocation status decision:')),
                ('notes', models.TextField(blank=True, help_text='Internal notes', max_length=512, verbose_name='Notes')),
                ('created_time', models.DateTimeField(blank=True, editable=False)),
                ('modified_time', models.DateTimeField(blank=True, editable=False)),
                ('started_date', models.DateTimeField(null=True)),
                ('completed_date', models.DateTimeField(null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_date', models.DateTimeField()),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='project.Project')),
            ],
            options={
                'verbose_name': 'historical rse allocation',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
        ),
        migrations.CreateModel(
            name='RSEAllocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='A one-sentence summary of the work to be done by the RSE team.', max_length=256, verbose_name='Subproject title')),
                ('software', models.TextField(help_text='The software currently in use to deliver the research outcomes. Questions to consider: Is it commercial, open-source, or in-house code? What language is it written in? What libraries does it depend on? Is it parallelised?', max_length=2000, verbose_name='Software description')),
                ('duration', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Estimated duration (in weeks)')),
                ('goals', models.TextField(help_text='Describe in as much detail as possible what you would like the RSE team to achieve. What steps are necessary to achieve this?', max_length=5000, verbose_name='Project goals')),
                ('outcomes', models.TextField(help_text='What effect will the completion of this work have on your research, e.g. in terms of publications or grants enabled? ', max_length=2000, verbose_name='Project outcomes')),
                ('confidentiality', models.TextField(blank=True, help_text='Is the research or code restricted from being published openly and presented at conferences and other events related to research software? If so, please describe the restrictions.', max_length=1000, verbose_name='Confidentiality constraints')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Awaiting Approval'), (1, 'Approved; awaiting RSE time'), (2, 'Declined'), (3, 'In progress'), (4, 'Completed'), (5, 'Closed')], default=0, verbose_name='Current Status')),
                ('previous_status', models.PositiveSmallIntegerField(choices=[(0, 'Awaiting Approval'), (1, 'Approved; awaiting RSE time'), (2, 'Declined'), (3, 'In progress'), (4, 'Completed'), (5, 'Closed')], default=0, verbose_name='Previous Status')),
                ('reason_decision', models.TextField(blank=True, max_length=256, verbose_name='Reason for the RSE allocation status decision:')),
                ('notes', models.TextField(blank=True, help_text='Internal notes', max_length=512, verbose_name='Notes')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
                ('started_date', models.DateTimeField(null=True)),
                ('completed_date', models.DateTimeField(null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
    ]
