# Generated by Django 2.0.2 on 2018-08-15 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0047_historicalrseallocation_rseallocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalrseallocation',
            old_name='started_date',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='rseallocation',
            old_name='started_date',
            new_name='start_date',
        ),
    ]
