# Generated by Django 2.0.2 on 2018-08-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0048_auto_20180815_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrseallocation',
            name='completed_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalrseallocation',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rseallocation',
            name='completed_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='rseallocation',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
