# Generated by Django 2.0.2 on 2018-08-16 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0049_auto_20180815_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrseallocation',
            name='duration',
            field=models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01, 'Estimated duration must be a positive number of weeks.')], verbose_name='Estimated duration (in weeks)'),
        ),
        migrations.AlterField(
            model_name='rseallocation',
            name='duration',
            field=models.DecimalField(decimal_places=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01, 'Estimated duration must be a positive number of weeks.')], verbose_name='Estimated duration (in weeks)'),
        ),
    ]
