# Generated by Django 2.0.2 on 2018-09-20 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0050_auto_20180816_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='approved_by_supervisor',
            field=models.BooleanField(default=False, verbose_name='confirmed by Supervisor'),
        ),
        migrations.AddField(
            model_name='project',
            name='approved_by_supervisor',
            field=models.BooleanField(default=False, verbose_name='confirmed by Supervisor'),
        ),
    ]
