# Generated by Django 2.0.2 on 2018-09-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0050_auto_20180816_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='custom_user_cap',
            field=models.PositiveIntegerField(default=0, verbose_name='Custom user cap'),
        ),
        migrations.AddField(
            model_name='project',
            name='custom_user_cap',
            field=models.PositiveIntegerField(default=0, verbose_name='Custom user cap'),
        ),
    ]
