# Generated by Django 2.0.2 on 2018-09-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0051_auto_20180920_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='approved_by_supervisor',
            field=models.BooleanField(default=False, verbose_name='Confirmed by Supervisor'),
        ),
        migrations.AlterField(
            model_name='project',
            name='approved_by_supervisor',
            field=models.BooleanField(default=False, verbose_name='Confirmed by Supervisor'),
        ),
    ]
