# Generated by Django 2.0.2 on 2018-09-21 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0051_auto_20180919_1257'),
        ('project', '0052_auto_20180921_0852'),
    ]

    operations = [
    ]
