# Generated by Django 2.1.7 on 2019-06-25 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0053_merge_20180921_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='department',
            field=models.CharField(blank=True, help_text='Enter the department or other division of the university that the project will be based in', max_length=128, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='description',
            field=models.TextField(help_text='Write an abstract for the research that you will be doing in this project, including a description of what sort of computations will be done.', max_length=1024, verbose_name='Project Description'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='institution_reference',
            field=models.CharField(blank=True, help_text=' If your institution assigns identifiers to research projects, enter the identifier for this project here', max_length=128, verbose_name='Owning institution project reference'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='legacy_arcca_id',
            field=models.CharField(blank=True, help_text='If the project has previously made use of ARCCA resources and has an ARCCA ID, enter it here', max_length=50, verbose_name='Legacy ARCCA ID'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='legacy_hpcw_id',
            field=models.CharField(blank=True, help_text='If the project previously made use of the HPC Wales facilities, enter the ID here.', max_length=50, verbose_name='Legacy HPC Wales ID'),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='supervisor_email',
            field=models.CharField(blank=True, help_text='Enter the email address of the Project Leader named above.', max_length=256, verbose_name="Project Leader's email"),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='supervisor_name',
            field=models.CharField(blank=True, help_text='Enter the name of the member of staff who is leading this research. This need not be you, but should be a permanent member of University staff. If this research is funded, this would typically be the local Principal Investigator on the grant.', max_length=256, verbose_name="Project Leader's name"),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='supervisor_position',
            field=models.CharField(blank=True, help_text=' What position does the Project Leader named above hold? (For example, Lecturer, Professor, Head of Department)', max_length=256, verbose_name="Project Leader's position"),
        ),
        migrations.AlterField(
            model_name='historicalproject',
            name='title',
            field=models.CharField(help_text='Write a one-line description of the work you will be doing in this project.', max_length=256, verbose_name='Project Title'),
        ),
        migrations.AlterField(
            model_name='historicalsystemallocationrequest',
            name='end_date',
            field=models.DateField(help_text='When do you anticipate being finished with the system for this project?', verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='historicalsystemallocationrequest',
            name='start_date',
            field=models.DateField(help_text='When do you like to start using the system for this project?', verbose_name='Start date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='department',
            field=models.CharField(blank=True, help_text='Enter the department or other division of the university that the project will be based in', max_length=128, verbose_name='Department'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Write an abstract for the research that you will be doing in this project, including a description of what sort of computations will be done.', max_length=1024, verbose_name='Project Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='institution_reference',
            field=models.CharField(blank=True, help_text=' If your institution assigns identifiers to research projects, enter the identifier for this project here', max_length=128, verbose_name='Owning institution project reference'),
        ),
        migrations.AlterField(
            model_name='project',
            name='legacy_arcca_id',
            field=models.CharField(blank=True, help_text='If the project has previously made use of ARCCA resources and has an ARCCA ID, enter it here', max_length=50, verbose_name='Legacy ARCCA ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='legacy_hpcw_id',
            field=models.CharField(blank=True, help_text='If the project previously made use of the HPC Wales facilities, enter the ID here.', max_length=50, verbose_name='Legacy HPC Wales ID'),
        ),
        migrations.AlterField(
            model_name='project',
            name='supervisor_email',
            field=models.CharField(blank=True, help_text='Enter the email address of the Project Leader named above.', max_length=256, verbose_name="Project Leader's email"),
        ),
        migrations.AlterField(
            model_name='project',
            name='supervisor_name',
            field=models.CharField(blank=True, help_text='Enter the name of the member of staff who is leading this research. This need not be you, but should be a permanent member of University staff. If this research is funded, this would typically be the local Principal Investigator on the grant.', max_length=256, verbose_name="Project Leader's name"),
        ),
        migrations.AlterField(
            model_name='project',
            name='supervisor_position',
            field=models.CharField(blank=True, help_text=' What position does the Project Leader named above hold? (For example, Lecturer, Professor, Head of Department)', max_length=256, verbose_name="Project Leader's position"),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='Write a one-line description of the work you will be doing in this project.', max_length=256, verbose_name='Project Title'),
        ),
        migrations.AlterField(
            model_name='systemallocationrequest',
            name='end_date',
            field=models.DateField(help_text='When do you anticipate being finished with the system for this project?', verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='systemallocationrequest',
            name='start_date',
            field=models.DateField(help_text='When do you like to start using the system for this project?', verbose_name='Start date'),
        ),
    ]
