# Generated by Django 2.2.2 on 2019-07-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0054_auto_20190625_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsystemallocationrequest',
            name='allocation_cputime',
            field=models.PositiveIntegerField(blank=True, help_text='How many "core-hours" do you anticipate this project needing? For example, if you have a program that only uses one CPU on your laptop, and runs for 48 hours, and you need to run it 1000 times, then this number would be 48,000; if instead it used four cores on your laptop for the same amount of time, it would be 192,000.', null=True, verbose_name='CPU time allocation in hours'),
        ),
        migrations.AlterField(
            model_name='historicalsystemallocationrequest',
            name='allocation_memory',
            field=models.PositiveIntegerField(blank=True, help_text="How much memory will your program need at once per node? If you don't know this number, but know that the program runs on your computer, then enter the amount of RAM on your computer.", null=True, verbose_name='RAM allocation in GB'),
        ),
        migrations.AlterField(
            model_name='historicalsystemallocationrequest',
            name='allocation_storage_home',
            field=models.PositiveIntegerField(blank=True, help_text='Home storage is long-term (although not backed up) file storage used for data you need to keep on the system for months at a time. This is subject to a quota. Enter the amount of storage you need for the longer term; 100GB is the default size.', null=True, verbose_name='Home storage in GB'),
        ),
        migrations.AlterField(
            model_name='historicalsystemallocationrequest',
            name='allocation_storage_scratch',
            field=models.PositiveIntegerField(blank=True, help_text='Scratch storage is short-term file storage used for intermediary data you need temporarily, but will either delete or move off the system once it is no longer needed. There is no quota on scratch, but it is shared with other users, and when it is full, then old unused files will be deleted. Enter the amount of short-term intermediary storage you will need.', null=True, verbose_name='Scratch storage in GB'),
        ),
        migrations.AlterField(
            model_name='historicalsystemallocationrequest',
            name='document',
            field=models.TextField(blank=True, help_text='If you have any documentation that you feel Supercomputing Wales would benefit from seeing with regards to this project, or have been asked to include some documentation in your request, please attach it here.', max_length=100, null=True, verbose_name='Upload Supporting Documents'),
        ),
        migrations.AlterField(
            model_name='historicalsystemallocationrequest',
            name='requirements_onboarding',
            field=models.TextField(blank=True, help_text='Do you require any assistance in adapting your software to be able to make use of the system? If so, write details of this here.', max_length=512, verbose_name='Onboarding Requirements'),
        ),
        migrations.AlterField(
            model_name='historicalsystemallocationrequest',
            name='requirements_software',
            field=models.TextField(blank=True, help_text='Enter details of any software you require to be installed on the system to be able to use it for your research. Examples include compilers (Intel and GNU C, C++, and Fortran compilers are available already), interpreters (Python and R are available already), open-source libraries, and commercial software (e.g. Stata, Matlab, Molpro). In addition if you require a specific version of the software then please specify this.', max_length=512, verbose_name='Software Requirements'),
        ),
        migrations.AlterField(
            model_name='historicalsystemallocationrequest',
            name='requirements_training',
            field=models.TextField(blank=True, help_text='Do you require training in order to make use of the system? If so, write details of this here.', max_length=512, verbose_name='Training Requirements'),
        ),
        migrations.AlterField(
            model_name='systemallocationrequest',
            name='allocation_cputime',
            field=models.PositiveIntegerField(blank=True, help_text='How many "core-hours" do you anticipate this project needing? For example, if you have a program that only uses one CPU on your laptop, and runs for 48 hours, and you need to run it 1000 times, then this number would be 48,000; if instead it used four cores on your laptop for the same amount of time, it would be 192,000.', null=True, verbose_name='CPU time allocation in hours'),
        ),
        migrations.AlterField(
            model_name='systemallocationrequest',
            name='allocation_memory',
            field=models.PositiveIntegerField(blank=True, help_text="How much memory will your program need at once per node? If you don't know this number, but know that the program runs on your computer, then enter the amount of RAM on your computer.", null=True, verbose_name='RAM allocation in GB'),
        ),
        migrations.AlterField(
            model_name='systemallocationrequest',
            name='allocation_storage_home',
            field=models.PositiveIntegerField(blank=True, help_text='Home storage is long-term (although not backed up) file storage used for data you need to keep on the system for months at a time. This is subject to a quota. Enter the amount of storage you need for the longer term; 100GB is the default size.', null=True, verbose_name='Home storage in GB'),
        ),
        migrations.AlterField(
            model_name='systemallocationrequest',
            name='allocation_storage_scratch',
            field=models.PositiveIntegerField(blank=True, help_text='Scratch storage is short-term file storage used for intermediary data you need temporarily, but will either delete or move off the system once it is no longer needed. There is no quota on scratch, but it is shared with other users, and when it is full, then old unused files will be deleted. Enter the amount of short-term intermediary storage you will need.', null=True, verbose_name='Scratch storage in GB'),
        ),
        migrations.AlterField(
            model_name='systemallocationrequest',
            name='document',
            field=models.FileField(blank=True, help_text='If you have any documentation that you feel Supercomputing Wales would benefit from seeing with regards to this project, or have been asked to include some documentation in your request, please attach it here.', null=True, upload_to='documents/%Y/%m/%d/%M/', verbose_name='Upload Supporting Documents'),
        ),
        migrations.AlterField(
            model_name='systemallocationrequest',
            name='requirements_onboarding',
            field=models.TextField(blank=True, help_text='Do you require any assistance in adapting your software to be able to make use of the system? If so, write details of this here.', max_length=512, verbose_name='Onboarding Requirements'),
        ),
        migrations.AlterField(
            model_name='systemallocationrequest',
            name='requirements_software',
            field=models.TextField(blank=True, help_text='Enter details of any software you require to be installed on the system to be able to use it for your research. Examples include compilers (Intel and GNU C, C++, and Fortran compilers are available already), interpreters (Python and R are available already), open-source libraries, and commercial software (e.g. Stata, Matlab, Molpro). In addition if you require a specific version of the software then please specify this.', max_length=512, verbose_name='Software Requirements'),
        ),
        migrations.AlterField(
            model_name='systemallocationrequest',
            name='requirements_training',
            field=models.TextField(blank=True, help_text='Do you require training in order to make use of the system? If so, write details of this here.', max_length=512, verbose_name='Training Requirements'),
        ),
    ]
