# Generated by Django 2.2.2 on 2019-07-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0055_auto_20190701_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='attributions',
            field=models.ManyToManyField(blank=True, limit_choices_to={'attributions': None}, to='funding.Attribution'),
        ),
    ]
