# Generated by Django 2.2.2 on 2019-07-02 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0056_auto_20190702_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='attributions',
            field=models.ManyToManyField(blank=True, limit_choices_to={'Attribution': None}, to='funding.Attribution'),
        ),
    ]
