# Generated by Django 2.2.2 on 2019-07-02 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0059_auto_20190702_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='attributions',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(attributions=None), to='funding.Attribution'),
        ),
    ]
