# Generated by Django 2.2.2 on 2019-07-02 14:01

from django.db import migrations, models
import django.db.models.deletion
import funding.models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0011_auto_20180831_1531'),
        ('project', '0060_auto_20190702_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='attributions',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='funding.Attribution'),
        ),
        migrations.RemoveField(
            model_name='project',
            name='attributions',
        ),
        migrations.AddField(
            model_name='project',
            name='attributions',
            field=models.ForeignKey(blank=True, default=None, limit_choices_to=models.Q(('attributions', None), ('attributions', funding.models.Attribution), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='funding.Attribution'),
        ),
    ]
