# Generated by Django 2.2.2 on 2019-07-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funding', '0011_auto_20180831_1531'),
        ('project', '0062_auto_20190702_1502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='attributions',
        ),
        migrations.RemoveField(
            model_name='project',
            name='attributions',
        ),
        migrations.AddField(
            model_name='project',
            name='attributions',
            field=models.ManyToManyField(blank=True, default=None, limit_choices_to=models.Q(attributions=None), to='funding.Attribution'),
        ),
    ]
