# Generated by Django 2.2.2 on 2019-07-02 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0064_auto_20190702_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='attributions',
            field=models.ManyToManyField(blank=True, default=None, limit_choices_to=models.Q(Attribution=None), to='funding.Attribution'),
        ),
    ]
