# Generated by Django 2.2.2 on 2019-07-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0065_auto_20190702_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='attributions',
            field=models.ManyToManyField(blank=True, default=None, related_name='_project_attributions_+', to='project.Project'),
        ),
    ]
