# Generated by Django 2.2.2 on 2019-07-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0066_auto_20190703_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='attributions',
            field=models.ManyToManyField(blank=True, default=None, to='funding.Attribution'),
        ),
    ]
