# Generated by Django 2.2.2 on 2019-07-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0067_auto_20190703_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='attributions',
            field=models.ManyToManyField(blank=True, to='funding.Attribution'),
        ),
    ]
