# Generated by Django 2.2.2 on 2019-07-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0068_auto_20190703_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='Attribution_points',
            field=models.IntegerField(default=50000, editable=False, help_text='Calculated Attribution points for this project', verbose_name='Attribution points (Ap)'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='Qos',
            field=models.IntegerField(default=1, editable=False, help_text='Quality of service value for this project, to be input into slurm.', verbose_name='Quality of Service (QOS)'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='prioritized_time',
            field=models.IntegerField(default=0, editable=False, help_text='Sum of priortized cpu time alocated to this project', verbose_name='Total prioritized time'),
        ),
        migrations.AddField(
            model_name='project',
            name='Attribution_points',
            field=models.IntegerField(default=50000, editable=False, help_text='Calculated Attribution points for this project', verbose_name='Attribution points (Ap)'),
        ),
        migrations.AddField(
            model_name='project',
            name='Qos',
            field=models.IntegerField(default=1, editable=False, help_text='Quality of service value for this project, to be input into slurm.', verbose_name='Quality of Service (QOS)'),
        ),
        migrations.AddField(
            model_name='project',
            name='prioritized_time',
            field=models.IntegerField(default=0, editable=False, help_text='Sum of priortized cpu time alocated to this project', verbose_name='Total prioritized time'),
        ),
    ]
