# Generated by Django 2.1.7 on 2019-07-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0070_auto_20190717_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='Ap',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Current attribution points'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='Qos',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Current Qualitty of service level'),
        ),
        migrations.AddField(
            model_name='project',
            name='Ap',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Current attribution points'),
        ),
        migrations.AddField(
            model_name='project',
            name='Qos',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Current Qualitty of service level'),
        ),
    ]
