# Generated by Django 2.2.4 on 2019-08-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0071_auto_20190724_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproject',
            name='Ap',
        ),
        migrations.RemoveField(
            model_name='historicalproject',
            name='Qos',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Ap',
        ),
        migrations.RemoveField(
            model_name='project',
            name='Qos',
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='QOS',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Quality of Service level at last update'),
        ),
        migrations.AddField(
            model_name='historicalproject',
            name='active_AP',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Attribution points at last update'),
        ),
        migrations.AddField(
            model_name='project',
            name='QOS',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Quality of Service level at last update'),
        ),
        migrations.AddField(
            model_name='project',
            name='active_AP',
            field=models.PositiveIntegerField(default=None, null=True, verbose_name='Attribution points at last update'),
        ),
    ]
