# Generated by Django 2.2.4 on 2019-10-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0072_auto_20190813_2148_squashed_0073_auto_20190814_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprojectusermembership',
            name='in_ldap',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectusermembership',
            name='in_ldap',
            field=models.BooleanField(default=True),
        ),
    ]
