# Generated by Django 2.2.4 on 2019-08-14 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0072_auto_20190813_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalproject',
            old_name='active_AP',
            new_name='active_attribution_points',
        ),
        migrations.RenameField(
            model_name='historicalproject',
            old_name='QOS',
            new_name='quality_of_service',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='active_AP',
            new_name='active_attribution_points',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='QOS',
            new_name='quality_of_service',
        ),
    ]
