# Generated by Django 2.0.2 on 2018-03-25 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0002_auto_20180324_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='base_domain',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
