# Generated by Django 2.0.2 on 2018-03-26 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0003_institution_base_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='identity_provider',
            new_name='identity_provider_login',
        ),
        migrations.AddField(
            model_name='institution',
            name='identity_provider_logout',
            field=models.URLField(blank=True),
        ),
    ]
