# Generated by Django 2.0.2 on 2018-06-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0007_auto_20180514_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='identity_provider',
            field=models.URLField(blank=True, verbose_name='Shibboleth Identity Provider'),
        ),
    ]
