# Generated by Django 2.0.2 on 2018-08-07 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0009_auto_20180807_1327'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='local_repository_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
