# Generated by Django 2.0.2 on 2018-08-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0010_institution_local_repository_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='local_repository_domain',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
