# Generated by Django 2.0.2 on 2018-08-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0011_institution_local_repository_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='funding_database_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
