# Generated by Django 2.0.2 on 2018-08-30 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0014_institution_rse_notify_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='needs_funding_approval',
            field=models.BooleanField(default=False),
        ),
    ]
