# Generated by Django 2.0.2 on 2018-09-06 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0015_institution_needs_funding_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='funding_document_email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
