# Generated by Django 2.0.2 on 2018-09-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0017_auto_20180906_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='default_project_user_cap',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
