# Generated by Django 2.0.2 on 2018-09-19 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0018_institution_needs_user_approval'),
        ('institution', '0018_institution_default_project_user_cap'),
    ]

    operations = [
    ]
