# Generated by Django 2.0.2 on 2018-09-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0019_merge_20180919_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='needs_user_approval',
            field=models.BooleanField(default=True),
        ),
    ]
