# Generated by Django 2.0.2 on 2019-01-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0009_institution_support_email'),
        ('institution', '0021_institution_needs_supervisor_approval'),
    ]

    operations = [
    ]
