# Generated by Django 2.1.2 on 2019-03-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0015_auto_20180821_1530'),
        ('institution', '0022_merge_20190106_1501'),
    ]

    operations = [
    ]
