# Generated by Django 2.2.1 on 2019-05-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0022_merge_20190106_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='needs_funding_workflow',
            field=models.BooleanField(default=False),
        ),
    ]
