# Generated by Django 2.1.7 on 2019-05-01 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0023_merge_20190304_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='needs_legacy_inst_id',
        ),
    ]
