# Generated by Django 2.1.7 on 2019-05-02 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0024_remove_institution_needs_legacy_inst_id'),
        ('institution', '0023_institution_needs_funding_workflow'),
    ]

    operations = [
    ]
