# Generated by Django 2.1.7 on 2019-05-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0025_merge_20190502_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='allows_rse_requests',
            field=models.BooleanField(default=False, verbose_name='Allow RSE requests'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='rse_notify_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='RSE notification email'),
        ),
    ]
