# Generated by Django 2.1.7 on 2019-07-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0026_auto_20190502_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='needs_priority_workflow',
            field=models.BooleanField(default=False),
        ),
    ]
