# Generated by Django 2.2.1 on 2019-08-02 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0028_auto_20190802_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='funding_database_name',
            new_name='funding_database_entry_name',
        ),
    ]
