# Generated by Django 2.2.4 on 2019-08-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution', '0029_auto_20190802_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='AP_base',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='institution',
            name='AP_per_CPU_hour',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='institution',
            name='AP_per_GPU_hour',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='institution',
            name='AP_per_publication',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
